apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-git-source-srnq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-git-source-srnq
    app.kubernetes.io/part-of: build-suite-test-application-vxbn
  name: build-suite-test-component-git-source-srnq
  namespace: build-templates-e2e
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: build-suite-test-component-git-source-srnq
    weight: 100
status: {}
